#define PARAMS_LIST_SIZE 30
#define PARAM_LEN 50
#define COMMAND_SIZE PARAM_LEN + PARAM_LEN *PARAMS_LIST_SIZE
#define HISTORY_LEN 100
#define BG_JOBS_SIZE 100
#define RUN_BACKGROUND '&'
#define REDIRECT_STDOUT '>'
#define REDIRECT_STDOUT_APPEND ">>"
#define REDIRECT_STDIN '<'
#define REDIRECT_STDIN_APPEND "<<"
